server:
  port: 8989
  servlet:
    context-path: /d3
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  group:
    exerciseDebug: com.example.d3.exercise
    principleInfo: com.example.d3.principle
  level:
    exerciseDebug: debug
    principleInfo: info
    sql: debug

# 这里是tom配置类
tom:
  name: 我是tom
  age: 13
# pig配置类
pig:
  name: 他是pig
  age: 1
sheep:
  id: 1
  name: 我是sheep
  age: 44
#
spring:
  datasource:
    url: jdbc:mysql://47.97.63.174:3306/wordpr
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wangCh788@990
  redis:
   cluster:
    nodes: 47.97.63.174:6381,47.97.63.174:6382,47.97.63.174:6383,47.97.63.174:6384,47.97.63.174:6385,47.97.63.174:6386
    max-redirects: 5
    connectionTimeout: 1000
    soTimeout: 1000
    jedis:
      pool:
        max-active: 20
        max-idle: 0
        max-wait: -1
  #host:47.97.63.174
      #user:admin
      #pwd:wcMq@88999
  rabbitmq:
    host: 47.97.63.174
    username: admin
    password: wcMq@88999
    publisher-confirm-type: correlated
    publisher-returns: true
  kafka:
    bootstrap-servers: hadoop101:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#指定mapper映射文件位置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
