package com.example.d3;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.mybatis.spring.annotation.MapperScan;

// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
@MapperScan(basePackages = "com.example.d3.lock.synctest.mysql.mapper")
public class D3Application {

    public static void main(String[] args) {
        SpringApplication.run(D3Application.class, args);
    }

}
